app/special_line/__init__.py
from flask import Blueprint

special_line = Blueprint('special_line', __name__)

from . import views

app/special_line/views.py
import os, logging
from ..import create_app
from flask import render_template, session, redirect, url_for, current_app, request, abort, g, Response, flash
from flask_login import login_required, current_user
import datetime
from datetime import date
from ..models import SpecialLine
from . import special_line
from .common import get_saps
from .. import db
from ..main.common import get_host


@special_line.route('/special_line', methods=['GET', 'POST'])
@login_required
def index():
    search_date = date.today()
    city = session.get('city')
    if not city:
        return redirect(url_for('main.city_list'))
    host_list = get_host(city)
    
    if request.method == 'POST':
        host_name = request.form.get('host_name')
        form_date = request.form.get('date')
        if form_date:
            search_date = datetime.datetime.strptime(form_date,'%Y-%m-%d').date()
    else:
        host_name = request.args.get('host_name')
        if not host_name:
            host_name = host_list[0]

    if host_name == 'all':
        special_line_data = SpecialLine.query.filter_by(date_time = search_date).all()
        if not special_line_data:
            last = SpecialLine.query.order_by(SpecialLine.id.desc()).first()
            if last:
                special_line_data = SpecialLine.query.filter_by(date_time = last.date_time).all()
    else:
        special_line_data = SpecialLine.query.filter_by(host_name = host_name, date_time = search_date).all()
        if not special_line_data:
            last = SpecialLine.query.filter_by(host_name = host_name).order_by(SpecialLine.id.desc()).first()
            if last:
                special_line_data = SpecialLine.query.filter_by(host_name = host_name, date_time = last.date_time).all()

    special_line_data = [(index, item) for index, item in enumerate(special_line_data) ]
    return render_template('report/special_line.html', host_name=host_name, host_list = host_list, special_line_data = special_line_data ,action='special_line')

def save_special_line(city, host_name, config):
    '''专线统计入库'''

    # app = create_app('production')
    # app.app_context().push()
    today_data_count = SpecialLine.query.filter_by(host_name = host_name, date_time = date.today()).count()

    if today_data_count:
        logging.info('special_line host: {} today is saved'.format(host_name))
        # db.session.close()
        return

    special_line_data = get_saps(config)
    if special_line_data:
        logging.info('special_line host: {} {} begin save'.format(host_name, 'special_line_data'))

    today = date.today()
    for item in special_line_data:

        #存入数据库
        special_line = SpecialLine(
            city = city,
            host_name = host_name,
            service = item[0],
            service_id = item[1],
            ies_describe = item[2],
            gi_name = item[3],
            gi_describe = item[4],
            sap_name = item[5],
            ip = item[6],
            mac = item[7],
            egress_id = item[8],
            rate = item[9],
            date_time = today
        )

        db.session.add(special_line)
    db.session.commit()
    db.session.close()

@special_line.route('/user_cmp', methods=['GET', 'POST'])
@login_required
def user_cmp():
    '''用户对比'''

    b_date = date.today() - datetime.timedelta(days=1)
    e_date = date.today()
    city = session.get('city')
    if not city:
        return redirect(url_for('main.city_list'))
    host_list = get_host(city)

    if request.method == 'POST':
        host_name = request.form.get('host_name')
        b_form_date = request.form.get('b_date')
        e_form_date = request.form.get('e_date')
        if b_form_date:
            b_date = datetime.datetime.strptime(b_form_date,'%Y-%m-%d').date()
        if e_form_date:
            e_date = datetime.datetime.strptime(e_form_date,'%Y-%m-%d').date()
    else:
        host_name = host_list[0]

    b_date_data = SpecialLine.query.filter_by(host_name = host_name, date_time = b_date).all()
    e_date_data = SpecialLine.query.filter_by(host_name = host_name, date_time = e_date).all()

    b_date_ip = []
    e_date_ip = []
    for i in b_date_data:
        b_date_ip.append(i.ip)

    for i in e_date_data:
        e_date_ip.append(i.ip)

    new_data = []
    live_data = []

    for i in e_date_data:
        if i.ip not in b_date_ip:
            new_data.append(i)

    for i in b_date_data:
        if i.ip not in e_date_ip:
            live_data.append(i)
    
    new_data = [(index, item) for index, item in enumerate(new_data)]
    live_data = [(index, item) for index, item in enumerate(live_data)]
    return render_template(
        'report/user_cmp.html', 
        host_name=host_name, 
        host_list = host_list, 
        new_data = new_data, 
        live_data = live_data, 
        action='special_line')

app/templates/report/address_collect_download.html
{% extends "report_port.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 专线地址采集 {% endblock %}

{% block report_content %}
<div class="row">
    <div class="col-md-6">
        <form action="{{ url_for('main.address_mk_excel') }}" method="post">
            {% if host_data %}
                <a class="btn btn-default selectAll">全选</a>
                <button type="submit" class="btn btn-default">下载</button>
            {% endif %}
            <table class="table table-striped table-condensed" >
                <tbody>
                    {% for index, item in host_data %}
                    <tr>
                        <th>{{ index + 1 }}</th>
                        <th>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="{{ item }}"> {{ item }}
                                </label>
                            </div>
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if host_data %}
                <a class="btn btn-default selectAll">全选</a>
                <button type="submit" class="btn btn-default">下载</button>
            {% endif %}
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  $(function() {
    $(".selectAll").click(function(){ 
        $("input").each(function(){
            if ($(this).prop("checked")) {
                $(this).prop("checked",false);
            } else {
                $(this).prop("checked",true);
            }
        });
    })
  });
</script>
{% endblock %}

app/templates/report/install_base.html
{% extends "report_port.html" %}

{% block title %} InstallBase统计表 {% endblock %}
{% block page_header %} InstallBase统计表 {% endblock %}

{% block report_content %}
<a class="btn btn-default" href="{{ url_for('main.download_excel', host_name = 'aaa', table_name = 'install_base') }}" role="button">生成表格</a>
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>序号</th>
                <th>采集日期</th>
                <th>省份</th>
                <th>运营商</th>
                <th>业务类型</th>
                <th>网络类型</th>
                <th>设备类型</th>
                <th>设备型号</th>
                <th>版本</th>
                <th>数量</th>
                <th>备注</th>
            </tr>
        </thead>
        <tbody>
            {% for index, item in data %}
                <tr>
                    <th>{{ index + 1 }}</th>
                    <th>{{ item.date_time }}</th>
                    <th>{{ item.province }}</th>
                    <th>{{ item.operator }}</th>
                    <th>{{ item.busines_type }}</th>
                    <th>{{ item.net_type }}</th>
                    <th>{{ item.host_type }}</th>
                    <th>{{ item.host_model }}</th>
                    <th>{{ item.version }}</th>
                    <th>{{ item.number }}</th>
                    <th>{{ item.note }}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/report/nat_port.html
{% extends "report_port.html" %}

{% block title %} NatPort统计表 {% endblock %}
{% block page_header %} NatPort统计表 {% endblock %}

{% block report_content %}
<form class="form-inline" method="post" action="{{ url_for('main.nat_port') }}">
    <div class="form-group">
        <label>设备名称</label>
        <select class="form-control" name = "host_name">
            {% if host_name == 'all' %}
            <option selected value ="all">全部</option>
            {% else %}
            <option value ="all">全部</option>
            {% endif %}
            {% for i in host_list %}
                {% if i == host_name %}
                <option selected>{{ i }}</option>
                {% else %}
                <option>{{ i }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>日期</label>
        <div class="input-group date form_datetime" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1">
            <input class="form-control" type="text" id="port_statistic_date"  name="date" value="{{ date }}" readonly>
            <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
            <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
        </div>
    </div>
    <button type="submit" class="btn btn-default">查看</button>
    <a class="btn btn-default" href="{{ url_for('main.download_excel', host_name = host_name, table_name = 'nat_port') }}" role="button">生成表格</a>
</form><br>
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>序号</th>
                <th>采集日期</th>
                <th>设备名</th>
                <th>端口号</th>
                <th>利用率</th>
            </tr>
        </thead>
        <tbody>
            {% for index, item in data %}
                <tr>
                    <th>{{ index + 1 }}</th>
                    <th>{{ item.date_time }}</th>
                    <th>{{ item.host_name }}</th>
                    <th>{{ item.port }}</th>
                    <th>{{ item.utilization }}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/report/net_flow.html
{% extends "report_port.html" %}

{% block title %} 重要网络流量统计表 {% endblock %}
{% block page_header %} 重要网络流量统计表 {% endblock %}

{% block report_content %}
<a class="btn btn-default" href="{{ url_for('main.download_excel', host_name = 'ccc', table_name = 'net_flow') }}" role="button">生成表格</a>
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>采集日期</th>
                <th>Carrier</th>
                <th>Province</th>
                <th>City</th>
                <th>Network</th>
                <th>Site Name</th>
                <th>10G Port Num</th>
                <th>10G Port Utilization</th>
                <th>100G Port Num</th>
                <th>100G Port Utilization</th>
                <th>Peak Uplink Throughput Utilization</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data %}
                <tr>
                    <th>{{ item.date_time }}</th>
                    <th>{{ item.carrier }}</th>
                    <th>{{ item.province }}</th>
                    <th>{{ item.city }}</th>
                    <th>{{ item.network }}</th>
                    <th>{{ item.site_name }}</th>
                    <th>{{ item.port_num_10g }}</th>
                    <th>{{ item.port_utilization_10g }}</th>
                    <th>{{ item.port_num_100g }}</th>
                    <th>{{ item.port_utilization_100g }}</th>
                    <th>{{ item.pea_uplink_throughput_utilization }}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/report/service_statistic.html
{% extends "statistic_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block data_content %}
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">上传统计</div>
            <div class="panel-body">
                {{ wtf.quick_form(form, url_for('main.upload_service_statistic')) }}
            </div>
        </div>
        <form action="{{ url_for('main.service_mk_excel') }}" method="post">
            {% if host_list %}
                <a class="btn btn-default selectAll">全选</a>
                <button type="submit" class="btn btn-default">下载</button>
            {% endif %}
            <table class="table table-striped table-condensed" >
                <tbody>
                    {% for index, item in host_list %}
                    <tr>
                        <th>{{ index + 1 }}</th>
                        <th>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="{{ item }}"> {{ item }}
                                </label>
                            </div>
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if host_list %}
                <a id="selectAll" class="btn btn-default">全选</a>
                <button type="submit" class="btn btn-default">下载</button>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  $(function() {
    $(".selectAll").click(function(){ 
        $("input").each(function(){
            if ($(this).prop("checked")) {
                $(this).prop("checked",false);
            } else {
                $(this).prop("checked",true);
            }
        });
    })
  });
</script>
{% endblock %}

app/templates/report/special_line.html
{% extends "report_port.html" %}

{% block title %} 专线统计表 {% endblock %}
{% block page_header %} 专线统计表 {% endblock %}

{% block report_content %}
<form class="form-inline" method="post" action="{{ url_for('special_line.index') }}">
    <div class="form-group">
        <label>设备名称</label>
        <select class="form-control" name = "host_name">
            {% if host_name == 'all' %}
            <option selected value ="all">全部</option>
            {% else %}
            <option value ="all">全部</option>
            {% endif %}
            {% for i in host_list %}
                {% if i == host_name %}
                <option selected>{{ i }}</option>
                {% else %}
                <option>{{ i }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>日期</label>
        <div class="input-group date form_datetime" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1">
            <input class="form-control" type="text" id="port_statistic_date"  name="date" value="" readonly>
            <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
            <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
        </div>
    </div>
    <button type="submit" class="btn btn-default">查看</button>
    <a class="btn btn-default" href="{{ url_for('main.download_excel', host_name = host_name, table_name = 'special_line') }}" role="button">生成表格</a>
    <a class="btn btn-default" href="{{ url_for('special_line.user_cmp') }}" role="button">用户对比</a>
</form><br>
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>序号</th>
                <th>采集日期</th>
                <th>Service</th>
                <th>Service编号</th>
                <th>IES描述</th>
                <th>interface端口名称</th>
                <th>interface端口描述</th>
                <th>sap信息</th>
                <th>IP地址</th>
                <th>MAC地址</th>
                <th>qos sap-egress编号</th>
                <th>带宽值</th>
            </tr>
        </thead>
        <tbody>
            {% for index, item in special_line_data %}
                <tr>
                    <th>{{ index + 1 }}</th>
                    <th>{{ item.date_time }}</th>
                    <th>{{ item.service }}</th>
                    <th>{{ item.service_id }}</th>
                    <th>{{ item.ies_describe }}</th>
                    <th>{{ item.gi_name }}</th>
                    <th>{{ item.gi_describe }}</th>
                    <th>{{ item.sap_name }}</th>
                    <th>{{ item.ip }}</th>
                    <th>{{ item.mac }}</th>
                    <th>{{ item.egress_id }}</th>
                    <th>{{ item.rate }}</th>
                    <th>{{ item.date_time }}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/report/user_cmp.html
{% extends "report_port.html" %}

{% block title %} 专线统计表 {% endblock %}
{% block page_header %} 专线统计表 {% endblock %}

{% block report_content2 %}
<form class="form-inline" method="post" action="{{ url_for('special_line.index') }}">
    <div class="form-group">
        <label>设备名称</label>
        <select class="form-control" name = "host_name">
            {% for i in host_list %}
                {% if i == host_name %}
                <option selected>{{ i }}</option>
                {% else %}
                <option>{{ i }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>起始日期</label>
        <div class="input-group date form_datetime" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1">
            <input class="form-control" type="text" id="b_date"  name="b_date" value="" readonly>
            <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
            <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
        </div>
    </div>
    <div class="form-group">
        <label>结束日期</label>
        <div class="input-group date form_datetime" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1">
            <input class="form-control" type="text" id="e_date" name="e_date" value="" readonly>
            <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
            <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
        </div>
    </div>
    <a class="btn btn-default" href="{{ url_for('special_line.user_cmp') }}" role="button">用户对比</a>
</form><br>
    <h2>新增用户</h2>
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>序号</th>
                <th>采集日期</th>
                <th>Service</th>
                <th>Service编号</th>
                <th>IES描述</th>
                <th>interface端口名称</th>
                <th>interface端口描述</th>
                <th>sap信息</th>
                <th>IP地址</th>
                <th>MAC地址</th>
                <th>qos sap-egress编号</th>
                <th>带宽值</th>
            </tr>
        </thead>
        <tbody>
            {% for index, item in new_data %}
                <tr>
                    <th>{{ index + 1 }}</th>
                    <th>{{ item.date_time }}</th>
                    <th>{{ item.service }}</th>
                    <th>{{ item.service_id }}</th>
                    <th>{{ item.ies_describe }}</th>
                    <th>{{ item.gi_name }}</th>
                    <th>{{ item.gi_describe }}</th>
                    <th>{{ item.sap_name }}</th>
                    <th>{{ item.ip }}</th>
                    <th>{{ item.mac }}</th>
                    <th>{{ item.egress_id }}</th>
                    <th>{{ item.rate }}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>离网用户</h2>
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>序号</th>
                <th>采集日期</th>
                <th>Service</th>
                <th>Service编号</th>
                <th>IES描述</th>
                <th>interface端口名称</th>
                <th>interface端口描述</th>
                <th>sap信息</th>
                <th>IP地址</th>
                <th>MAC地址</th>
                <th>qos sap-egress编号</th>
                <th>带宽值</th>
            </tr>
        </thead>
        <tbody>
            {% for index, item in live_data %}
                <tr>
                    <th>{{ index + 1 }}</th>
                    <th>{{ item.date_time }}</th>
                    <th>{{ item.service }}</th>
                    <th>{{ item.service_id }}</th>
                    <th>{{ item.ies_describe }}</th>
                    <th>{{ item.gi_name }}</th>
                    <th>{{ item.gi_describe }}</th>
                    <th>{{ item.sap_name }}</th>
                    <th>{{ item.ip }}</th>
                    <th>{{ item.mac }}</th>
                    <th>{{ item.egress_id }}</th>
                    <th>{{ item.rate }}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}